[project]
name = "call-me-maybe2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "devinesm", email = "inesmonteirosara@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.5.3",
    "pydantic>=2.13.5",
]

[project.scripts]
call-me-maybe2 = "call_me_maybe2:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
