[project]
name = "call-me-maybe"
version = "0.1.0"
description = "Call Me Maybe - LLM Function Calling Tool"
readme = "README.md"
authors = [
    { name = "ipinto-m", email = "ipinto-m@student.42porto.com" }
]
requires-python = ">=3.10"
dependencies = [
    "llm-sdk",
    "numpy",
    "pydantic",
]

[project.scripts]
call-me-maybe2 = "call_me_maybe2:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[tool.uv.workspace]
members = [
    "llm_sdk",
]

[tool.uv.sources]
llm-sdk = { workspace = true }

[tool.mypy]
python_version = "3.14"
explicit_package_bases = true
mypy_path = ["llm_sdk"]

[dependency-groups]
dev = [
    "flake8>=7.3.0",
    "mypy>=2.3.1",
]
